module.exports = {
  apps: [
    {
      name: 'orca-api',
      cwd: './apps/api',
      script: 'dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: { NODE_ENV: 'production' },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      time: true,
    },
    {
      name: 'orca-engine',
      cwd: './apps/engine',
      script: 'dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: { NODE_ENV: 'production' },
      error_file: './logs/engine-error.log',
      out_file: './logs/engine-out.log',
      time: true,
    },
    {
      name: 'orca-web',
      cwd: './apps/web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: { NODE_ENV: 'production' },
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      time: true,
    },
  ],
};
